import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import { GameProvider } from "@/context/GameContext";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR" className={`${sora.variable} antialiased`}>
      <body>
        <GameProvider>
          <main className="max-w-360 mx-auto w-full px-4 font-sans">
            <Header />
            {children}
          </main>
        </GameProvider>
      </body>
    </html>
  );
}
